export interface RoleData {
  slug: string;
  title: string;
  department: string;
  type: string;
  location: string;
  level: string;
  salary: string;
  overview: string;
  responsibilities: string[];
  requirements: string[];
  niceToHave: string[];
}

export const allRoles: RoleData[] = [
  {
    slug: "senior-penetration-tester",
    title: "Senior Penetration Tester",
    department: "Cybersecurity",
    type: "Full-time",
    location: "Remote / USA",
    level: "Senior",
    salary: "$130,000 – $165,000",
    overview:
      "Aegis Interlink is seeking a Senior Penetration Tester to lead offensive security engagements across federal agencies, defense contractors, and Fortune 500 clients. You will design and execute red team operations, web application assessments, and network penetration tests — delivering intelligence that drives measurable security improvements.",
    responsibilities: [
      "Lead end-to-end penetration testing across web, network, and cloud environments",
      "Develop custom exploits, scripts, and tooling to support advanced attack simulations",
      "Produce executive-level and technical reports with findings, risk ratings, and remediation steps",
      "Mentor junior analysts and contribute to internal methodology development",
      "Scope engagements, manage timelines, and present findings to client stakeholders",
      "Track emerging vulnerabilities, CVEs, and offensive security techniques",
    ],
    requirements: [
      "5+ years of hands-on penetration testing experience",
      "Proficiency with Metasploit, Burp Suite, Cobalt Strike, Nmap, and BloodHound",
      "Deep knowledge of OWASP Top 10, PTES, and NIST frameworks",
      "Experience with Active Directory attacks (Kerberoasting, Pass-the-Hash, DCSync)",
      "Ability to obtain a U.S. security clearance (existing clearance preferred)",
      "OSCP, GPEN, or equivalent certification required",
    ],
    niceToHave: [
      "Active Top Secret / SCI clearance",
      "Red team adversary simulation experience",
      "Cloud security testing expertise (AWS, Azure, GCP)",
      "Open-source security contributions or CVE disclosures",
    ],
  },
  {
    slug: "soc-analyst-tier-2",
    title: "SOC Analyst",
    department: "Cybersecurity",
    type: "Full-time",
    location: "Remote / USA",
    level: "Mid",
    salary: "$90,000 – $115,000",
    overview:
      "As a SOC Analyst at Aegis Interlink, you will be a key responder in our 24/7 Security Operations Center — investigating escalated alerts, conducting threat hunting, and driving incident response for federal and enterprise clients across SIEM, EDR, and threat intelligence platforms.",
    responsibilities: [
      "Investigate and triage Tier 1 escalations with speed and precision",
      "Conduct proactive threat hunting across SIEM, EDR, and threat intel platforms",
      "Lead incident response including containment, eradication, and recovery",
      "Produce detailed incident reports and post-mortems for clients",
      "Tune detection rules and reduce false positive rates in the SIEM",
      "Collaborate with Tier 3 analysts and engineers on complex threat scenarios",
    ],
    requirements: [
      "3+ years of SOC or incident response experience",
      "Hands-on experience with SIEM platforms (Splunk, Microsoft Sentinel, or equivalent)",
      "Strong command of the MITRE ATT&CK framework",
      "Experience with network forensics, log analysis, and malware triage",
      "Ability to work rotating shifts in a 24/7 environment",
      "Security+ or CySA+ required; CEH or GCIH preferred",
    ],
    niceToHave: [
      "Experience supporting federal agency SOC operations",
      "Python or PowerShell scripting for SOC automation",
      "Familiarity with SOAR platforms",
      "Active government security clearance",
    ],
  },
  {
    slug: "cloud-security-engineer",
    title: "Cloud Security Engineer",
    department: "Cybersecurity",
    type: "Full-time",
    location: "Remote / USA",
    level: "Senior",
    salary: "$125,000 – $155,000",
    overview:
      "Aegis Interlink is looking for a Cloud Security Engineer to design and implement security controls across multi-cloud environments. You will partner with cloud architects to embed security into infrastructure-as-code, automate compliance checks, and respond to cloud-native threats for government and enterprise clients.",
    responsibilities: [
      "Design and implement security architectures across AWS, Azure, and GCP",
      "Build and maintain cloud security posture management (CSPM) solutions",
      "Integrate security into CI/CD pipelines using DevSecOps principles",
      "Automate compliance checks for FedRAMP, FISMA, and SOC 2",
      "Conduct cloud-focused threat modeling and risk assessments",
      "Respond to cloud security incidents and perform root cause analysis",
    ],
    requirements: [
      "4+ years of cloud security engineering experience",
      "Deep expertise in at least one major cloud provider (AWS preferred)",
      "Experience with IaC tools (Terraform or CloudFormation)",
      "Proficiency with Prisma Cloud, Wiz, AWS Security Hub, or equivalent",
      "Understanding of zero-trust architecture principles",
      "AWS Security Specialty or CCSP certification required",
    ],
    niceToHave: [
      "FedRAMP authorization experience",
      "Kubernetes security and container hardening knowledge",
      "Familiarity with CNAPP and runtime security tooling",
      "Existing security clearance",
    ],
  },
  {
    slug: "full-stack-engineer",
    title: "Full-Stack Engineer (Next.js / Node)",
    department: "Software Development",
    type: "Full-time",
    location: "Remote / USA",
    level: "Mid",
    salary: "$110,000 – $140,000",
    overview:
      "Join Aegis Interlink's engineering team to build secure, high-performance web applications and APIs for government and enterprise clients. You'll work across the full stack — from React/Next.js frontends to Node.js backends and cloud-hosted databases — in an agile environment that values code quality and engineering excellence.",
    responsibilities: [
      "Design, build, and maintain full-stack applications using Next.js and Node.js",
      "Develop RESTful APIs and integrate third-party services and data pipelines",
      "Collaborate with designers, product managers, and security engineers",
      "Write clean, well-tested code with a focus on performance and accessibility",
      "Participate in code reviews and contribute to architectural decisions",
      "Deploy and monitor applications in cloud environments (AWS or Azure)",
    ],
    requirements: [
      "3+ years of full-stack development experience",
      "Expert-level proficiency in TypeScript, React, and Next.js",
      "Strong Node.js and REST API design skills",
      "Experience with PostgreSQL or other relational databases",
      "Familiarity with CI/CD pipelines and Git workflows",
      "Understanding of web security best practices (OWASP Top 10)",
    ],
    niceToHave: [
      "Experience with federal government software delivery",
      "Familiarity with GraphQL, Prisma, or tRPC",
      "Docker/Kubernetes containerization knowledge",
      "Open-source contributions",
    ],
  },
  {
    slug: "software-engineer-entry-level",
    title: "Software Engineer (Entry Level)",
    department: "Software Development",
    type: "Full-time",
    location: "Remote / USA",
    level: "Junior",
    salary: "$95,000 – $120,000",
    overview:
      "Aegis Interlink is looking for motivated entry-level Software Engineers to join our growing development team. This is a fantastic opportunity to kick-start your career building real-world applications for government and enterprise clients, with direct mentorship from senior engineers and a clear path for rapid growth.",
    responsibilities: [
      "Contribute to front-end and back-end features under the guidance of senior engineers",
      "Write clean, readable, and well-tested code following team conventions",
      "Participate in code reviews to learn best practices and improve code quality",
      "Help debug and resolve issues across the application stack",
      "Collaborate with cross-functional teams including design, product, and security",
      "Document code changes and contribute to internal knowledge bases",
    ],
    requirements: [
      "Bachelor's degree in Computer Science, Software Engineering, or equivalent experience",
      "Foundational knowledge of JavaScript or TypeScript and at least one backend language",
      "Understanding of basic web technologies (HTML, CSS, REST APIs)",
      "Familiarity with Git and version control workflows",
      "Strong problem-solving skills and eagerness to learn",
      "Excellent written and verbal communication skills",
    ],
    niceToHave: [
      "Personal or academic projects built with React, Next.js, or Node.js",
      "Internship or co-op experience in a software development role",
      "Exposure to cloud platforms (AWS, Azure, or GCP)",
      "Interest in cybersecurity or government technology",
    ],
  },
  {
    slug: "devsecops-engineer",
    title: "DevSecOps Engineer",
    department: "Software Development",
    type: "Full-time",
    location: "Remote / USA",
    level: "Senior",
    salary: "$120,000 – $150,000",
    overview:
      "Aegis Interlink is hiring a DevSecOps Engineer to bridge development, operations, and security for our clients. You will build and maintain secure CI/CD pipelines, automate security testing, and champion a shift-left security culture across engineering teams.",
    responsibilities: [
      "Design and maintain secure CI/CD pipelines integrating SAST, DAST, and SCA tools",
      "Automate infrastructure provisioning and configuration management using IaC",
      "Implement container security scanning and runtime protection for Kubernetes workloads",
      "Collaborate with developers to remediate security findings early in the SDLC",
      "Monitor production environments and respond to operational security events",
      "Build internal tooling and playbooks to accelerate secure software delivery",
    ],
    requirements: [
      "4+ years of DevOps or DevSecOps engineering experience",
      "Proficiency with CI/CD platforms (GitHub Actions, GitLab CI, Jenkins)",
      "Hands-on Terraform, Ansible, or equivalent IaC experience",
      "Experience integrating Snyk, Veracode, Checkmarx, or similar tools",
      "Strong Linux and scripting skills (Bash, Python)",
      "Kubernetes and Docker security best practices knowledge",
    ],
    niceToHave: [
      "CKS (Certified Kubernetes Security Specialist)",
      "Federal software supply chain security experience",
      "SBOM generation and management knowledge",
      "Existing security clearance",
    ],
  },
  {
    slug: "mobile-developer-react-native",
    title: "Mobile Developer (React Native)",
    department: "Software Development",
    type: "Contract",
    location: "Remote / USA",
    level: "Mid",
    salary: "$85 – $110 / hr",
    overview:
      "Aegis Interlink is seeking a contract Mobile Developer to build and maintain cross-platform mobile applications for government and enterprise clients. You will collaborate with our full-stack engineering team to deliver performant, accessible, and secure mobile experiences on iOS and Android.",
    responsibilities: [
      "Build and maintain cross-platform iOS and Android apps using React Native",
      "Integrate apps with RESTful APIs and third-party SDKs",
      "Implement mobile security best practices including secure storage and certificate pinning",
      "Optimize app performance across a wide range of device types",
      "Collaborate with designers to translate wireframes into polished UI components",
      "Maintain clear technical documentation and participate in code reviews",
    ],
    requirements: [
      "3+ years of React Native development experience",
      "Published apps in the App Store and/or Google Play",
      "Strong TypeScript skills and familiarity with React Navigation",
      "Experience with native module integration (iOS/Android bridges)",
      "Understanding of mobile UX patterns and accessibility standards",
      "State management experience (Redux, Zustand, or similar)",
    ],
    niceToHave: [
      "Experience with Expo and EAS Build",
      "Knowledge of mobile security testing and OWASP MASVS",
      "Prior work on regulated-industry mobile apps",
      "Background in React/Next.js web development",
    ],
  },
  {
    slug: "cloud-architect",
    title: "Cloud Architect (AWS/Azure)",
    department: "Cloud & Infrastructure",
    type: "Full-time",
    location: "Remote / USA",
    level: "Lead",
    salary: "$145,000 – $185,000",
    overview:
      "As a Cloud Architect at Aegis Interlink, you will lead the design and delivery of large-scale cloud solutions for federal agencies and enterprise organizations. You will serve as a trusted advisor to clients — translating complex business requirements into resilient, cost-effective, and secure cloud architectures.",
    responsibilities: [
      "Lead cloud architecture design across AWS and Azure for multi-account environments",
      "Define cloud strategy, governance models, and technical roadmaps for clients",
      "Oversee migrations including lift-and-shift, re-platforming, and re-architecting",
      "Establish landing zone patterns, network architecture, and identity frameworks",
      "Serve as technical lead and mentor for junior cloud engineers",
      "Present architectural recommendations to executive and C-suite stakeholders",
    ],
    requirements: [
      "8+ years of cloud engineering and architecture experience",
      "AWS Solutions Architect Professional or Azure Solutions Architect Expert certification",
      "Deep expertise in networking, IAM, security, and cost optimization",
      "Track record delivering cloud solutions for large enterprises or government",
      "Strong communication for both technical and executive audiences",
      "Experience with AWS Control Tower or Azure Landing Zones",
    ],
    niceToHave: [
      "FedRAMP High authorization experience",
      "Google Cloud Professional Architect certification",
      "FinOps practices and cloud cost optimization expertise",
      "Existing Top Secret clearance",
    ],
  },
  {
    slug: "infrastructure-engineer",
    title: "Infrastructure Engineer",
    department: "Cloud & Infrastructure",
    type: "Full-time",
    location: "Remote / USA",
    level: "Mid",
    salary: "$95,000 – $125,000",
    overview:
      "Aegis Interlink is looking for an Infrastructure Engineer to design, deploy, and maintain on-premise and hybrid infrastructure for government and enterprise clients. You will work hands-on with servers, networking equipment, virtualization platforms, and cloud integrations in highly secure environments.",
    responsibilities: [
      "Deploy and maintain physical and virtual server infrastructure (VMware, Hyper-V)",
      "Configure and manage enterprise networking (Cisco, Palo Alto, Fortinet)",
      "Implement and maintain backup, DR, and business continuity solutions",
      "Manage Active Directory, DNS, DHCP, and PKI infrastructure",
      "Collaborate with security teams to ensure infrastructure hardening and compliance",
      "Provide Tier 3 escalation support for infrastructure incidents",
    ],
    requirements: [
      "4+ years of enterprise infrastructure engineering experience",
      "Strong hands-on VMware vSphere or Microsoft Hyper-V skills",
      "Experience configuring Layer 2/3 networking (VLANs, BGP, OSPF)",
      "Proficiency with Windows Server and Linux system administration",
      "ITIL service management framework knowledge",
      "Ability to obtain a government security clearance",
    ],
    niceToHave: [
      "SCIF or classified network environment experience",
      "Cisco CCNP or equivalent networking certification",
      "SD-WAN solution familiarity",
      "Existing security clearance",
    ],
  },
  {
    slug: "data-engineer",
    title: "Data Engineer",
    department: "Data & Analytics",
    type: "Full-time",
    location: "Remote / USA",
    level: "Mid",
    salary: "$105,000 – $135,000",
    overview:
      "Aegis Interlink is seeking a Data Engineer to build and maintain scalable data pipelines for government and enterprise clients. You will architect ingestion frameworks, manage cloud data warehouses, and partner with analysts to ensure high-quality, accessible data that drives mission-critical decisions.",
    responsibilities: [
      "Design, build, and maintain robust ETL/ELT pipelines using modern tooling",
      "Manage and optimize cloud data warehouses (Snowflake, BigQuery, or Redshift)",
      "Implement data quality frameworks, monitoring, and alerting",
      "Collaborate with data scientists and analysts to surface reliable datasets",
      "Build data catalogs and maintain lineage and governance documentation",
      "Ensure pipelines meet FedRAMP, HIPAA, and compliance requirements",
    ],
    requirements: [
      "3+ years of data engineering experience",
      "Proficiency in Python and SQL for data transformation",
      "Hands-on experience with Apache Airflow, dbt, or similar tools",
      "Experience with Snowflake, BigQuery, or AWS Redshift",
      "Understanding of data modeling (star schema, data vault)",
      "Familiarity with Kafka, Kinesis, or Pub/Sub for streaming data",
    ],
    niceToHave: [
      "Federal data environment experience with strict governance",
      "Knowledge of dbt Cloud and Semantic Layer",
      "Apache Spark or large-scale batch processing experience",
      "Data mesh architecture experience",
    ],
  },
  {
    slug: "ml-ai-solutions-architect",
    title: "ML/AI Solutions Architect",
    department: "Data & Analytics",
    type: "Full-time",
    location: "Remote / USA",
    level: "Lead",
    salary: "$150,000 – $190,000",
    overview:
      "Aegis Interlink is hiring an ML/AI Solutions Architect to lead the design and delivery of machine learning and AI solutions for federal and enterprise clients. You will advise on AI strategy, architect end-to-end ML systems, and guide engineering teams from prototype to production deployment.",
    responsibilities: [
      "Lead AI/ML solution design from problem framing through production deployment",
      "Architect scalable MLOps pipelines for model training, evaluation, and monitoring",
      "Advise clients on responsible AI frameworks, bias mitigation, and explainability",
      "Collaborate with data engineers on feature engineering and data pipelines",
      "Evaluate and recommend AI platforms, frameworks, and third-party services",
      "Present AI strategies and architectures to C-suite and agency leadership",
    ],
    requirements: [
      "7+ years of machine learning or data science experience, 2+ in an architecture role",
      "Deep expertise in Python and ML frameworks (PyTorch, TensorFlow, scikit-learn)",
      "Experience deploying ML models at scale (MLflow, SageMaker, or Vertex AI)",
      "Strong knowledge of LLMs, RAG architectures, and generative AI patterns",
      "Track record delivering AI solutions in regulated industries",
      "Excellent communication skills for technical and executive stakeholders",
    ],
    niceToHave: [
      "Federal AI governance framework and ATO process experience",
      "AWS Machine Learning Specialty or Google Professional ML Engineer",
      "Background in NLP, computer vision, or time-series forecasting",
      "Existing security clearance",
    ],
  },
  {
    slug: "technical-support-representative",
    title: "Technical Support Representative",
    department: "Managed IT",
    type: "Full-time",
    location: "Remote / USA",
    level: "Junior",
    salary: "$55,000 – $70,000",
    overview:
      "Aegis Interlink is seeking a Technical Support Representative to serve as the first point of contact for our managed IT clients. You will resolve day-to-day technical issues, deliver outstanding customer service, and ensure client environments stay running smoothly — all while building the foundational skills to grow into a long-term IT career.",
    responsibilities: [
      "Serve as Tier 1 support for inbound tickets, calls, and chat requests from managed IT clients",
      "Diagnose and resolve common hardware, software, and connectivity issues",
      "Escalate complex issues to Tier 2 and Tier 3 teams with detailed documentation",
      "Set up and configure workstations, printers, VPNs, and business applications",
      "Maintain accurate records in the ticketing system (ServiceNow, Zendesk, or similar)",
      "Provide a positive, professional experience with every client interaction",
    ],
    requirements: [
      "1+ year of IT support or helpdesk experience (internship counts)",
      "Working knowledge of Windows 10/11 and Microsoft 365",
      "Ability to troubleshoot network connectivity, VPN, and peripheral hardware issues",
      "Strong written and verbal communication skills",
      "Patience and professionalism when supporting non-technical users",
      "CompTIA IT Fundamentals (ITF+) or A+ certification preferred",
    ],
    niceToHave: [
      "Experience with remote support tools (TeamViewer, AnyDesk, or similar)",
      "Familiarity with Active Directory and user account management",
      "Knowledge of ITIL service management fundamentals",
      "Interest in pursuing Tier 2 or network/security specialization",
    ],
  },
  {
    slug: "tier-2-help-desk",
    title: "Tier 2 Help Desk Technician",
    department: "Managed IT",
    type: "Full-time",
    location: "Remote / USA",
    level: "Mid",
    salary: "$65,000 – $85,000",
    overview:
      "As a Tier 2 Help Desk Technician at Aegis Interlink, you will handle escalated support requests that require deeper technical investigation across networking, systems administration, and cloud applications. You will be a critical link between frontline support and our engineering teams, keeping client environments secure and operational.",
    responsibilities: [
      "Resolve escalated Tier 1 tickets involving servers, networking, and cloud services",
      "Administer user accounts, permissions, and group policies in Active Directory and Azure AD",
      "Troubleshoot and configure VPNs, firewalls, switches, and wireless access points",
      "Perform patch management, software deployments, and endpoint hardening via RMM tools",
      "Assist in onboarding new clients including environment documentation and device setup",
      "Mentor Tier 1 technicians and contribute to the internal knowledge base",
    ],
    requirements: [
      "3+ years of IT support experience, including at least 1 year at Tier 2",
      "Hands-on experience with Windows Server, Active Directory, and Group Policy",
      "Proficiency troubleshooting Microsoft 365, Exchange, and Teams",
      "Experience with RMM and PSA platforms (ConnectWise, SolarWinds, or equivalent)",
      "Solid understanding of TCP/IP, DNS, DHCP, and VPN technologies",
      "CompTIA Network+ or equivalent certification required",
    ],
    niceToHave: [
      "Microsoft 365 Certified: Modern Desktop Administrator or equivalent",
      "Experience supporting hybrid Azure AD / on-prem environments",
      "Familiarity with MDM platforms (Intune, Jamf)",
      "Ability to obtain a government security clearance",
    ],
  },
];

export function getRoleBySlug(slug: string): RoleData | undefined {
  return allRoles.find((r) => r.slug === slug);
}
